# Generated by Django 4.1 on 2022-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.TextField()),
                ('destination', models.TextField()),
                ('travel_time', models.IntegerField()),
            ],
            options={
                'db_table': 'route',
            },
        ),
    ]
